#!/usr/bin/env bash
# This bash script displays information about the subdomains

dns_info_analyzer() {
	result=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION'| tail -1 | awk '{print $4 " " $5}')
	echo "$result" "$2" | awk '{print "The subdomain " $3 " is a " $1 " record and points to " $2}'
}

if [ "$#" == 2 ]
then
	dns_info_analyzer "$1" "$2"
else
	dns_info_analyzer "$1" "www"
	dns_info_analyzer "$1" "lb-01"
	dns_info_analyzer "$1" "web-01"
	dns_info_analyzer "$1" "web-02"
fi
