#!/usr/bin/env bash
# This bash script Installs nginx webserver so that /redirect_me is redirecting to another page.

apt-get update
apt-get install nginx -y


echo "Hello World!" > /var/www/html/index.html

touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;

     location /redirect_me {
        return 301 https://google.com;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
