#!/usr/bin/env bash
# This bash script Installs nginx webserver to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get update
apt-get install nginx -y


echo "Hello World!" > /var/www/html/index.html

touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /custom_404.html;
    location /custom_404 {
      root /var/www/html;
      internal;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
