#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 32024-web-01 44.192.38.74:80 check\n\tserver 32024-web-02 35.174.176.158:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
