#!/usr/bin/env bash
# This bash script fixes the issues with nginx server problems from listening on port 80.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
echo "" > /run/nginx.pid
