#!/usr/bin/env bash
# This bash script fixes the issues with nginx server problems from listening on port 80.
apt-get update -y
apt-get install nginx -y
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
