#!/usr/bin/env bash
# This bash script Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $BASHPID > /var/run/myscript.pid
i=1
while ((i < 8))
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
	sleep 2
done
