#!/usr/bin/env bash
# This script prints texts and numbers depending on the condition set

i=1
while ((i <= 20))
do
	echo $i
	if ((i == 4))
	then
		echo "bad luck from China"
	elif ((i == 9))
	then
		echo "bad luck from Japan"
	elif ((i == 17))
	then
		echo "bad luck from Italy"
	fi
	((i+=1))
done
