#!/usr/bin/env bash
# This script prints texts and numbers depending on the condition set

i=1
while ((i <= 20))
do
	echo $i
	case $i in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((i+=1))
done
